language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
  
before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq
  
install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi
  # biicode
  - wget http://www.biicode.com/downloads/latest/ubuntu64
  - mv ubuntu64 bii-ubuntu64.deb
  - sudo dpkg -i bii-ubuntu64.deb && sudo apt-get -f install
  - rm bii-ubuntu64.deb
  - wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz
  - tar -xzf cmake-3.0.2-Linux-64.tar.gz
  - sudo cp -fR cmake-3.0.2-Linux-64/* /usr
  - rm -rf cmake-3.0.2-Linux-64
  - rm cmake-3.0.2-Linux-64.tar.gz
  - export TRAVIS_CXX=$CXX
script:
  - pwd
  - bii init -L
  - bii find
  - bii configure -DBII_BOOST_BUILD_J=16
  - bii build
##################### CHANGE WITH YOUR CUSTOM CHECKS OR TEST EXECUTION ##################
########################################################################################
env:
  global:
    - GCC_VERSION="4.9"
