language: cpp
addons:
  apt:
    sources:
      - kalakris-cmake
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - cmake
      - g++-4.9
cache: 
  directories:
    - build/external
  apt: true
compiler:
  - gcc
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/64463f491a9781e3b19b
    on_success: always # default: always
    on_failure: always # default: always
    on_start: never # default: always
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then CXX="clang++-3.5" CC="clang-3.5"; fi
  - mkdir -p build
  - cd build
  - cmake ..
script:
  - cmake --build .
  - ctest -V -C debug
  - ./fuzzy-database& 
  - cd ../ #Back to project root to run npm test
  - npm install && npm test

