language: cpp
#sudo: required
#dist: trusty
addons:
  apt:
    sources:
      - kalakris-cmake
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - cmake
      - g++-4.9
      - clang-3.5
cache: 
  directories:
    - build/external
  apt: true
compiler:
  - clang
  - gcc
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/64463f491a9781e3b19b
    on_success: always # default: always
    on_failure: always # default: always
    on_start: never # default: always
install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 # - sudo apt-get update -y
 # - sudo apt-get install -y g++-4.9
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CC" = "clang"]; then export CXX="clang++-3.5" CC="clang++-3.5"; fi
  - gcc --version
  - clang++ --version
  - cmake --version
  - mkdir -p build
  - cd build
  - cmake ..
script:
  - cmake --build .
  - ctest -V -C debug
