language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
install:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
script:
  - cmake --build .
##################### CHANGE WITH YOUR CUSTOM CHECKS OR TEST EXECUTION ##################
########################################################################################
env:
  global:
    - GCC_VERSION="4.9"
