language: cpp
compiler:
  - clang
  - gcc
install:
  - mdkir build
  - cd build
  - cmake ..
script:
  - cmake --build .
##################### CHANGE WITH YOUR CUSTOM CHECKS OR TEST EXECUTION ##################
########################################################################################
env:
  global:
    - GCC_VERSION="4.9"
