language: cpp
sudo: required
dist: trusty
cache:
  directories:
    - build/external
compiler:
  - clang
  - gcc
#addons:
#  apt:
#    sources:
#      - kalakris-cmake
#      - ubuntu-toolchain-r-test
#    packages:
#      - cmake
#      - clang
#      - gcc-4.8
#      - g++-4.8
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install g++-4.9
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - gcc --version
  - cmake --version
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=DEBUG
script:
  - cmake --build .
##################### CHANGE WITH YOUR CUSTOM CHECKS OR TEST EXECUTION ##################
########################################################################################
