language: cpp

install:
  - mkdir -p ".travis/biicode" && cd ".travis"
  - wget https://s3.amazonaws.com/biibinaries/release/3.3/bii-ubuntu-64_3_3.deb
  - dpkg -x bii-ubuntu-64_3_3.deb ./biicode/
  - cd biicode/opt/biicode
  - BIIPATH=$(pwd)
  - export PATH="$BIIPATH:$PATH"
  - bii setup:cpp
  - biicode configure

script: biicode build

compiler:
  - gcc
  - clang

os:
  - linux