language: cpp
compiler:
  - clang
  - gcc
install:
  - pwd
  - ls
  - mkdir -p ".travis/biicode" && cd ".travis"
  - wget https://s3.amazonaws.com/biibinaries/release/3.3/bii-ubuntu-64_3_3.deb
  - dpkg -x bii-ubuntu-64_3_3.deb ./biicode/
  - cd biicode/opt/biicode
  - BIIPATH=$(pwd)
  - export PATH="$BIIPATH:$PATH"
  - cd /home/travis/build/matann/fuzzy-database
script:
  - pwd
  - bii init -L
  - bii find
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++" && bii build; fi
  - if [ "$CXX" == "g++" ];     then export CXX="g++"     && bii build; fi
##################### CHANGE WITH YOUR CUSTOM CHECKS OR TEST EXECUTION ##################
########################################################################################
env:
  global:
    - GCC_VERSION="4.9"