language: cpp
#sudo: required
addons:
  apt:
    sources:
    - george-edison55/precise-backports
    packages:
    - gcc-4.8
    - g++-4.8
    - biicode
compiler:
  - clang
  - gcc
script:
  - pwd
  - bii buzz
##################### CHANGE WITH YOUR CUSTOM CHECKS OR TEST EXECUTION ##################
########################################################################################
env:
  global:
    - GCC_VERSION="4.9"