language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - kalakris-cmake
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-4.8
      - g++-4.8
install:
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=DEBUG
script:
  - cmake --build .
##################### CHANGE WITH YOUR CUSTOM CHECKS OR TEST EXECUTION ##################
########################################################################################
