language: cpp
sudo: required
dist: trusty
cache:
  directories:
    - build/external
compiler:
  - clang
  - gcc
webhooks:
  urls:
    - https://webhooks.gitter.im/e/64463f491a9781e3b19b
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: false     # default: false
install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -y
  - sudo apt-get install -y g++-4.9
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - gcc --version
  - cmake --version
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=DEBUG
script:
  - cmake --build .
##################### CHANGE WITH YOUR CUSTOM CHECKS OR TEST EXECUTION ##################
########################################################################################